# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
imports:
    - { resource: security.yml }

parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%klink.api.client_secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        cookie_lifetime: 31536000

    fragments:       ~
    http_method_override: true
    serializer:
        enabled: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    paths:
        "%kernel.root_dir%/../src/AppBundle": AppBundle
    globals:
        assetUrl: "%asset_url%"
        prodMode: "%prod_mode%"
        apiEndpoint: "%klink.api.end_point%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [AppBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
#        uglifyjs2:
#            bin: /usr/local/bin/uglifyjs
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
            #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
#    assets:
#        jquery_and_ui:
#            inputs:
#                - 'AppBundle/Resources/public/assets/vendors/jquery/dist/jquery.min.js'

api:
    klink_api:
        end_point: %klink.api.end_point%
        client_id: %klink.api.client_id%
        client_secret: %klink.api.client_secret%