api:
    resource: "@ApiBundle/Resources/config/routing/main.yml"

app:
    resource: "@AppBundle/Resources/config/routing/main.yml"

# todo remove dummy routes
dummy-routes:
    resource: "@AppBundle/Controller/"
    type:     annotation